[metadata]
name = "Celeste"
box_art = "/mnt/games/Games/banner/celeste.png"
release_year = 2018
path_to_game = "/mnt/games/Games/celeste-linux/Celeste"
runner = "native"

# this serves as override for general settings
[general]

# this serves as override for the native runner settings
[native]
