[metadata]
name = "Va-11 Hall-a : Cyberpunk Bartender Action"
box_art = "/mnt/games/Games/banner/va-11 hall-a.png"
release_year = 2016
path_to_game = "/mnt/games/Games/VA-11 Hall-A - Cyberpunk Bartender Action/Launch VA-11 Hall-A - Cyberpunk Bartender Action.lnk"
runner = "wine"

# this serves as override for general settings
[general]

# this serves as override for the native runner settings
[wine]
