[package]
name = "game_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version="0.7.0", features=["glow", "image"]} # so we use glow because iced doesn't seem to do that well with wgpu
iced_aw = {path="iced_aw"}
image = "0.24.5"
toml = "0.5.10"
log = "0.4.17"
pretty_env_logger = "0.4.0"
