[general]
mangohud = true
mesa_prime = true
nv_prime = true
vk_icd_loader = '/etc/vulkan/icd.d/nvidia_icd.json'

[metadata]
box_art = ''

[rpcs3]
path_to_rpcs3 = '/mnt/games/rpcs3-v0.0.27-14893-a767beec_linux64.AppImage'

[ryujinx]
path_to_ryujinx = '/mnt/games/ryujinx/Ryujinx'

[wine]
dxvk_nvapi_path = './dxvk_nvapi0.6/'
dxvk_path = './dxvk-2.0/'
esync = true
fsync = true
path_to_wine = '/mnt/part2/owned/dev/game_handler/wine-tkg-staging-fsync-git-opt-8.0.r6.g33879905/bin/wine'
use_dxvk = true
use_dxvk_nvapi = true
use_vkd3d = true
vkd3d_path = './vkd3d-proton-2.8/'
